server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.1.12/jpa?characterEncoding=utf-8
    username: root
    password: lcex123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #不加这句则默认为myisam引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect